package com.zhs.haoyangde.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATION.
 */
public class Location {

    private Integer area_id_db;
    private Integer area_id;
    private Integer store_id;
    private String contact_province;
    private String contact_city;
    private String contact_district;
    private String distance;
    private String area_name;
    private String store_name;
    private Integer state;

    public Location() {
    }

    public Location(Integer area_id_db) {
        this.area_id_db = area_id_db;
    }

    public Location(Integer area_id_db, Integer area_id, Integer store_id, String contact_province, String contact_city, String contact_district, String distance, String area_name, String store_name, Integer state) {
        this.area_id_db = area_id_db;
        this.area_id = area_id;
        this.store_id = store_id;
        this.contact_province = contact_province;
        this.contact_city = contact_city;
        this.contact_district = contact_district;
        this.distance = distance;
        this.area_name = area_name;
        this.store_name = store_name;
        this.state = state;
    }

    public Integer getArea_id_db() {
        return area_id_db;
    }

    public void setArea_id_db(Integer area_id_db) {
        this.area_id_db = area_id_db;
    }

    public Integer getArea_id() {
        return area_id;
    }

    public void setArea_id(Integer area_id) {
        this.area_id = area_id;
    }

    public Integer getStore_id() {
        return store_id;
    }

    public void setStore_id(Integer store_id) {
        this.store_id = store_id;
    }

    public String getContact_province() {
        return contact_province;
    }

    public void setContact_province(String contact_province) {
        this.contact_province = contact_province;
    }

    public String getContact_city() {
        return contact_city;
    }

    public void setContact_city(String contact_city) {
        this.contact_city = contact_city;
    }

    public String getContact_district() {
        return contact_district;
    }

    public void setContact_district(String contact_district) {
        this.contact_district = contact_district;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getArea_name() {
        return area_name;
    }

    public void setArea_name(String area_name) {
        this.area_name = area_name;
    }

    public String getStore_name() {
        return store_name;
    }

    public void setStore_name(String store_name) {
        this.store_name = store_name;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
