package com.zhs.haoyangde.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT.
 */
public class Product {

    private Long product_id;
    private Integer product_number;

    public Product() {
    }

    public Product(Long product_id) {
        this.product_id = product_id;
    }

    public Product(Long product_id, Integer product_number) {
        this.product_id = product_id;
        this.product_number = product_number;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public Integer getProduct_number() {
        return product_number;
    }

    public void setProduct_number(Integer product_number) {
        this.product_number = product_number;
    }

}
