package com.zhs.haoyangde.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT.
 */
public class Product {

    private long product_id;
    private int product_number;
    private Double product_price_db;

    public Product() {
    }

    public Product(long product_id) {
        this.product_id = product_id;
    }

    public Product(long product_id, int product_number, Double product_price_db) {
        this.product_id = product_id;
        this.product_number = product_number;
        this.product_price_db = product_price_db;
    }

    public long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(long product_id) {
        this.product_id = product_id;
    }

    public int getProduct_number() {
        return product_number;
    }

    public void setProduct_number(int product_number) {
        this.product_number = product_number;
    }

    public Double getProduct_price_db() {
        return product_price_db;
    }

    public void setProduct_price_db(Double product_price_db) {
        this.product_price_db = product_price_db;
    }

}
