/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dzl_ketchapp_stickhero_InstallApk */

#ifndef _Included_com_dzl_ketchapp_stickhero_InstallApk
#define _Included_com_dzl_ketchapp_stickhero_InstallApk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dzl_ketchapp_stickhero_InstallApk
 * Method:    getString2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dzl_ketchapp_stickhero_InstallApk_getString2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
